// Quando o Google Apps Script estiver pronto, cole a URL terminada em /exec aqui.
const GOOGLE_SHEETS_URL = "https://script.google.com/macros/s/AKfycby-y6OvQW3zfnpT3nBsG25WyyFKNA4SDlgjHx_ZmK0FeBcuPOWJhEq0i04Yu6F_aQAmyw/exec";
const form = document.querySelector("#registration-form"), steps = [...document.querySelectorAll(".form-step")], stepLabel = document.querySelector("#step-label"), progressBar = document.querySelector("#progress-bar"), nextButton = document.querySelector("#next-button"), backButton = document.querySelector("#back-button"), error = document.querySelector("#form-error");
let currentStep = 0, childCount = 0;
function childCard(index) { return `<article class="child-card"><div class="child-card-title"><h3>Criança ${index + 1}</h3>${index ? '<button class="remove-child" type="button">Remover</button>' : ''}</div><div class="fields"><label>Nome completo<input data-field="nome" required autocomplete="name"></label><div class="two-columns"><label>Data de nascimento<input data-field="nascimento" type="date" required></label><label>Idade<input data-field="idade" type="number" min="0" max="12" readonly required></label></div><fieldset><legend>A criança é:</legend><div class="choices"><label><input data-field="genero" type="radio" name="genero-${index}" value="Menino" required> Menino</label><label><input data-field="genero" type="radio" name="genero-${index}" value="Menina"> Menina</label></div></fieldset><label>Possui alguma condição de saúde, alergia ou limitação?<textarea data-field="saude" placeholder="Se não houver, escreva “Não”." required></textarea></label><label>Faz uso de medicamento ou tem alguma observação importante?<textarea data-field="observacoes" placeholder="Se não houver, escreva “Não”." required></textarea></label></div></article>`; }
function sizeCard(index, name) { return `<article class="size-card"><h3>${name || `Criança ${index + 1}`}</h3><div class="two-columns"><label>Tamanho da roupa<input data-size="roupa" data-child="${index}" placeholder="Ex.: 8, 10 ou P" required></label><label>Número do calçado<input data-size="calcado" data-child="${index}" placeholder="Ex.: 32" required></label></div></article>`; }
function addChild() { document.querySelector("#children-list").insertAdjacentHTML("beforeend", childCard(childCount)); childCount += 1; }
function renderSizes() { const cards = [...document.querySelectorAll(".child-card")]; document.querySelector("#sizes-list").innerHTML = cards.map((card, index) => sizeCard(index, card.querySelector('[data-field="nome"]').value)).join(""); }
function showStep() { steps.forEach((step, index) => step.classList.toggle("active", index === currentStep)); stepLabel.textContent = `Etapa ${currentStep + 1} de ${steps.length}`; progressBar.style.width = `${((currentStep + 1) / steps.length) * 100}%`; backButton.hidden = currentStep === 0; nextButton.innerHTML = currentStep === steps.length - 1 ? "Enviar formulário <span>✓</span>" : "Continuar <span>→</span>"; error.textContent = ""; }
function currentStepIsValid() { for (const field of steps[currentStep].querySelectorAll("input, textarea, select")) { if (!field.checkValidity()) { field.reportValidity(); return false; } } return true; }
function collectData() { const children = [...document.querySelectorAll(".child-card")].map((card, index) => ({ nome: card.querySelector('[data-field="nome"]').value, nascimento: card.querySelector('[data-field="nascimento"]').value, idade: card.querySelector('[data-field="idade"]').value, genero: card.querySelector('[data-field="genero"]:checked').value, saude: card.querySelector('[data-field="saude"]').value, observacoes: card.querySelector('[data-field="observacoes"]').value, tamanhoRoupa: document.querySelector(`[data-size="roupa"][data-child="${index}"]`).value, tamanhoCalcado: document.querySelector(`[data-size="calcado"][data-child="${index}"]`).value })); return { responsavel: form.responsavel.value, telefone: form.telefone.value, parentesco: form.parentesco.value, endereco: form.endereco.value, criancas: children }; }
document.querySelector("#add-child-button").addEventListener("click", addChild); document.querySelector("#children-list").addEventListener("click", event => { if (event.target.matches(".remove-child")) event.target.closest(".child-card").remove(); }); document.querySelector("#children-list").addEventListener("input", event => { if (event.target.dataset.field !== "nascimento" || !event.target.value) return; const nascimento = new Date(`${event.target.value}T12:00:00`), hoje = new Date(); let idade = hoje.getFullYear() - nascimento.getFullYear(); if (hoje < new Date(hoje.getFullYear(), nascimento.getMonth(), nascimento.getDate())) idade -= 1; event.target.closest(".child-card").querySelector('[data-field="idade"]').value = idade; });
nextButton.addEventListener("click", async () => { if (!currentStepIsValid()) return; if (currentStep < steps.length - 1) { if (currentStep === 0) renderSizes(); currentStep += 1; showStep(); return; } nextButton.disabled = true; nextButton.textContent = "Enviando..."; try { if (GOOGLE_SHEETS_URL) await fetch(GOOGLE_SHEETS_URL, { method: "POST", mode: "no-cors", body: JSON.stringify(collectData()) }); form.hidden = true; document.querySelector("#success-message").hidden = false; } catch { error.textContent = "Não foi possível enviar agora. Verifique sua conexão e tente novamente."; nextButton.disabled = false; showStep(); } });
backButton.addEventListener("click", () => { currentStep -= 1; showStep(); }); document.querySelector("#restart-button").addEventListener("click", () => { form.reset(); childCount = 0; document.querySelector("#children-list").innerHTML = ""; addChild(); currentStep = 0; form.hidden = false; document.querySelector("#success-message").hidden = true; showStep(); }); addChild(); showStep();
